### ISSUE TITLE
mongo

### ISSUE THREAD

**Issue by ajesses** [OmarElGabry/chat.io#10]
(node:11048) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

**Comment by ajesses** [comment]
mongoose4.13.0

**Comment by jebraieili** [comment]
in index.js file inner database directory set useMongoClient true
 `Mongoose.connect(dbURI, { useMongoClient: true });`
