### ISSUE TITLE
Remove authentication

### ISSUE THREAD

**Issue by datasleek** [OmarElGabry/chat.io#21]
Hi, I want to use this app but i don't want any authentication system.I just want to join room and start chatting.How can i achieve this? May you please list the steps which have to be performed to remove this authentication system.

I have uninstalled passport , passport-local , passport-twitter, passport-facebook modules from this app. What else should i do?

**Comment by OmarElGabry** [comment]
Uncomment any line for passport in [server.js](https://github.com/OmarElGabry/chat.io/blob/master/server.js#L30). Also, always return ``true`` from [isAuthenticated](https://github.com/OmarElGabry/chat.io/blob/master/app/models/user.js#L54)
