### ISSUE TITLE
Private messaging

### ISSUE THREAD

**Issue by saurabhchalke** [OmarElGabry/chat.io#8]
Hi,

This is a great little App indeed. I would like to know whether there is an option for private messaging in this?

Thanks!

**Comment by OmarElGabry** [comment]
Hey!

I don't know why I didn't come across this issue. It has been long time though. Sorry for that.

For your question, I am not sure what do mean by "private". The messages in a room are broadcasted only to that room. Not to everyone else. If you mean chat between one-to-one person, then that's another case, which you can implement easily, following the same pattern in this code.

Thanks.
