### ISSUE TITLE
room into error

### ISSUE THREAD

**Issue by poptong** [OmarElGabry/chat.io#9]
"stack": [
    "TypeError: Cannot read property 'id' of undefined",
    "    at /chat/app/socket/index.js:57:27",
    "    at /chat/node_modules/mongoose/lib/model.js:4056:16",
    "    at /chat/node_modules/mongoose/lib/services/model/applyHooks.js:175:17",
    "    at process._tickCallback (internal/process/next_tick.js:150:11)"
  ],
  "level": "error",
  "message": "uncaughtException: Cannot read property 'id' of undefined"

**Comment by Samhot** [comment]
Same error for me, anyone gets a solution ?

**Comment by A1iAshoor** [comment]
same here

**Comment by A1iAshoor** [comment]
@poptong @Samhot updating mongoose version to 5.0.0 in _package.json_ should fix the issue.

The debug log to this error is related to MongoDB:
`{"level":"error","message":"error: MongoError: Unknown modifier: $pushAll"}`

**Comment by OmarElGabry** [comment]
I updated the version of Mongoose to 5.x.x as suggested by @A1iAshoor . Hope that will solve the issue.
